Config = Config or {}
Config.BillingCommissions = { -- This is a percentage (0.10) == 10%
    mechanic = 0.10
}
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 244
Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "fa-solid fa-phone-alt",
        tooltipText = "Telefon",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#25d366",
        icon = "fab fa-whatsapp",
        tooltipText = "Whatsapp",
        tooltipPos = "top",
        style = "font-size: 2.8vh",
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "fa-solid fa-gear",
        tooltipText = "Setări",
        tooltipPos = "top",
        style = "font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["camera"] = {
        app = "camera",
        color = "#2B2B2B",
        icon = "fa-solid fa-camera",
        tooltipText = "Camera",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ["bank"] = {
        app = "bank",
        color = "#1D1B34",
        icon = "fa-solid fa-building-columns",
        style = "color: #55546D;",
        tooltipText = "Bancă",
        job = false,
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
    },
    ["gallery"] = {
        app = "gallery",
        color = "#6883ba",
        icon = "fa-solid fa-image",
        tooltipText = "Galerie",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 18,
        Alerts = 0,
    },
    ["mail"] = {
        app = "mail",
        color = "#fff",
        icon = "fas fa-envelope",
        tooltipText = "Mail",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 19,
        Alerts = 0,
    },
    ["calculator"] = {
        app = "calculator",
        color = "#c94001",
        icon = "fas fa-calculator",
        tooltipText = "Calculator",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 20,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#009ee5",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ["jobs"] = {
        app = "jobs",
        color = "#151515",
        color2 = "#161616",
        icon = "fas fa-id-badge",
        tooltipText = "Locuri de munca",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ["snake"] = {
        app = "snake",
        color = "#609",
        icon = "fas fa-ghost",
        tooltipText = "Snake Game",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["invest"] = {
        app = "invest",
        color = "#ffd43b80",
        icon = "fas fa-piggy-bank",
        tooltipText = "Investiții",
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
    ["premiumshop"] = {
        app = "premiumshop",
        color = "#78bd3a",
        icon = "fas fa-store",
        tooltipText = "Donații",
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ["taxi"] = {
        app = "taxi",
        color = "#ffc600",
        icon = "fas fa-taxi",
        tooltipText = "Taxi",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    }
}
Config.MaxSlots = 20

Config.StoreApps = {
    -- ["territory"] = {
    --     app = "territory",
    --     color = "#353b48",
    --     icon = "fas fa-globe-europe",
    --     tooltipText = "Territorium",
    --     tooltipPos = "right",
    --     style = "";
    --     job = false,
    --     blockedjobs = {},
    --     slot = 13,
    --     Alerts = 0,
    --     password = true,
    --     creator = "QBCore",
    --     title = "Territory",
    -- },
}
